image: fpco/stack-build:lts-8.5

pages:
  cache:
    paths:
      - _cache
      - .stack
  before_script:
    - export STACK_ROOT=`pwd`/.stack
    - stack setup --no-docker
    - stack install --no-docker --only-dependencies
    - stack build --no-docker
  script:
    - mkdir -p .public
    - stack exec site build --no-docker
    - mv _site/* .public/
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

