variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker build -t hugo:latest .
  script:
    - sed -i 's#^baseURL.*$#baseURL = "https://rlupton20.gitlab.io/blog/"#' blog/config.toml
    - docker run -v $(pwd)/blog:/mnt -w /mnt hugo:latest hugo
    - mv blog/public public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo Will copy files from build
  artifacts:
    paths:
      - public
  only:
    - master
