env:
  global:
    - HUGO_VERSION="0.59.0"

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xzvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin
  - hugo version

script:
  - pushd blog
  - sed -i 's#^baseURL.*$#baseURL = "https://rlupton20.github.io/"#' config.toml
  - hugo --gc --minify
  - popd
  - mv blog/public public

deploy:
  provider: pages
  repo: rlupton20/rlupton20.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
