env:
  global:
    - HUGO_VERSION="0.59.0"

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xzvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin
  - hugo version

script:
  - pushd blog
  - hugo --gc --minify
  - popd
  - mv blog/public public

